name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SERVER_PORT }}
          # タイムアウト時間を設定（ビルドに時間がかかる場合は長めに）
          timeout: 30m 
          script: |
            # プロジェクトのディレクトリに移動
            cd $HOME/SportEase

            ls $HOME
            ls /
            
            # 最新のコードを取得
            git fetch origin
            git merge origin/main
            
            # Dockerコンテナを再構築して起動
            # --build をつけることでDockerfileの変更も反映されます
            docker compose down -v

            docker compose -f docker-compose.production.yml build --no-cache
            docker compose -f docker-compose.production.yml up -d --build

            sleep 10

            docker compose -f docker-compose.production.yml up -d --build

            sleep 10

            docker compose -f docker-compose.production.yml up -d --build
            
            # 不要になった古いイメージを削除（ディスク容量節約）
            docker image prune -f